# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_affiliates_parlay_post_request import V1AffiliatesParlayPostRequest

class TestV1AffiliatesParlayPostRequest(unittest.TestCase):
    """V1AffiliatesParlayPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AffiliatesParlayPostRequest:
        """Test V1AffiliatesParlayPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AffiliatesParlayPostRequest`
        """
        model = V1AffiliatesParlayPostRequest()
        if include_optional:
            return V1AffiliatesParlayPostRequest(
                country_code = 'US',
                event_betting_market_position_ids = [
                    1
                    ],
                hide_offers_links = True,
                odds_format = 'american',
                offer_campaign = '',
                operator_ids = [
                    1
                    ],
                operator_keys = [
                    ''
                    ],
                product_mode = 'sportsbook',
                subnational_region_code = ''
            )
        else:
            return V1AffiliatesParlayPostRequest(
                event_betting_market_position_ids = [
                    1
                    ],
        )
        """

    def testV1AffiliatesParlayPostRequest(self):
        """Test V1AffiliatesParlayPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
