# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.auth_list_api_keys_response_api_keys_inner import AuthListAPIKeysResponseApiKeysInner

class TestAuthListAPIKeysResponseApiKeysInner(unittest.TestCase):
    """AuthListAPIKeysResponseApiKeysInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthListAPIKeysResponseApiKeysInner:
        """Test AuthListAPIKeysResponseApiKeysInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthListAPIKeysResponseApiKeysInner`
        """
        model = AuthListAPIKeysResponseApiKeysInner()
        if include_optional:
            return AuthListAPIKeysResponseApiKeysInner(
                active = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                key_code = '',
                name = '',
                widget = True
            )
        else:
            return AuthListAPIKeysResponseApiKeysInner(
        )
        """

    def testAuthListAPIKeysResponseApiKeysInner(self):
        """Test AuthListAPIKeysResponseApiKeysInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
