# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_v1_auth_login_post(self) -> None:
        """Test case for v1_auth_login_post

        Login with API key
        """
        pass

    def test_v1_auth_refresh_post(self) -> None:
        """Test case for v1_auth_refresh_post

        Refresh tokens
        """
        pass

    def test_v1_oauth_login_post(self) -> None:
        """Test case for v1_oauth_login_post

        OAuth login (client credentials)
        """
        pass

    def test_v1_oauth_refresh_post(self) -> None:
        """Test case for v1_oauth_refresh_post

        OAuth refresh
        """
        pass


if __name__ == '__main__':
    unittest.main()
