# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_affiliates_events_post_request import V1AffiliatesEventsPostRequest

class TestV1AffiliatesEventsPostRequest(unittest.TestCase):
    """V1AffiliatesEventsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AffiliatesEventsPostRequest:
        """Test V1AffiliatesEventsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AffiliatesEventsPostRequest`
        """
        model = V1AffiliatesEventsPostRequest()
        if include_optional:
            return V1AffiliatesEventsPostRequest(
                country_code = '01',
                device_type = 'ios',
                event_type = 'impression',
                offer_campaign = '',
                offer_id = '',
                offer_label = '',
                operator_id = 1,
                session_token = '',
                subnational_region_code = ''
            )
        else:
            return V1AffiliatesEventsPostRequest(
                country_code = '01',
                event_type = 'impression',
                offer_id = '',
                operator_id = 1,
        )
        """

    def testV1AffiliatesEventsPostRequest(self):
        """Test V1AffiliatesEventsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
