# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_trends_by_betting_market_position_post_request import V1TrendsByBettingMarketPositionPostRequest

class TestV1TrendsByBettingMarketPositionPostRequest(unittest.TestCase):
    """V1TrendsByBettingMarketPositionPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TrendsByBettingMarketPositionPostRequest:
        """Test V1TrendsByBettingMarketPositionPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TrendsByBettingMarketPositionPostRequest`
        """
        model = V1TrendsByBettingMarketPositionPostRequest()
        if include_optional:
            return V1TrendsByBettingMarketPositionPostRequest(
                event_betting_market_position_ids = [
                    1
                    ],
                odds_format = 'american',
                product_mode = 'sportsbook',
                use_cartoon_images = True
            )
        else:
            return V1TrendsByBettingMarketPositionPostRequest(
                event_betting_market_position_ids = [
                    1
                    ],
        )
        """

    def testV1TrendsByBettingMarketPositionPostRequest(self):
        """Test V1TrendsByBettingMarketPositionPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
