# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.api.events_api import EventsApi


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_events_upcoming_events_post(self) -> None:
        """Test case for v1_events_upcoming_events_post

        Get upcoming events
        """
        pass


if __name__ == '__main__':
    unittest.main()
