# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.auth_list_secrets_response_secrets_inner import AuthListSecretsResponseSecretsInner

class TestAuthListSecretsResponseSecretsInner(unittest.TestCase):
    """AuthListSecretsResponseSecretsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthListSecretsResponseSecretsInner:
        """Test AuthListSecretsResponseSecretsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthListSecretsResponseSecretsInner`
        """
        model = AuthListSecretsResponseSecretsInner()
        if include_optional:
            return AuthListSecretsResponseSecretsInner(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                secret_code = '',
                secret_preview = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AuthListSecretsResponseSecretsInner(
        )
        """

    def testAuthListSecretsResponseSecretsInner(self):
        """Test AuthListSecretsResponseSecretsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
