# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.api.references_api import ReferencesApi


class TestReferencesApi(unittest.TestCase):
    """ReferencesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReferencesApi()

    def tearDown(self) -> None:
        pass

    def test_v1_references_betting_market_categories_get(self) -> None:
        """Test case for v1_references_betting_market_categories_get

        Get betting market categories
        """
        pass

    def test_v1_references_betting_market_positions_get(self) -> None:
        """Test case for v1_references_betting_market_positions_get

        Get all betting market positions
        """
        pass

    def test_v1_references_betting_markets_get(self) -> None:
        """Test case for v1_references_betting_markets_get

        Get betting markets (paginated)
        """
        pass

    def test_v1_references_countries_get(self) -> None:
        """Test case for v1_references_countries_get

        Get countries (paginated)
        """
        pass

    def test_v1_references_event_periods_get(self) -> None:
        """Test case for v1_references_event_periods_get

        Get event periods
        """
        pass

    def test_v1_references_leagues_get(self) -> None:
        """Test case for v1_references_leagues_get

        Get leagues (paginated)
        """
        pass

    def test_v1_references_odds_format_get(self) -> None:
        """Test case for v1_references_odds_format_get

        Get odds formats (paginated)
        """
        pass

    def test_v1_references_operators_get(self) -> None:
        """Test case for v1_references_operators_get

        Get operators (paginated)
        """
        pass

    def test_v1_references_players_get(self) -> None:
        """Test case for v1_references_players_get

        Get players (paginated)
        """
        pass

    def test_v1_references_sports_get(self) -> None:
        """Test case for v1_references_sports_get

        Get sports (paginated)
        """
        pass

    def test_v1_references_subnational_regions_get(self) -> None:
        """Test case for v1_references_subnational_regions_get

        Get subnational regions (paginated)
        """
        pass

    def test_v1_references_tag_dimensions_get(self) -> None:
        """Test case for v1_references_tag_dimensions_get

        Get tag dimensions
        """
        pass

    def test_v1_references_tag_types_search_get(self) -> None:
        """Test case for v1_references_tag_types_search_get

        Search tag types
        """
        pass

    def test_v1_references_tag_types_tag_type_id_children_get(self) -> None:
        """Test case for v1_references_tag_types_tag_type_id_children_get

        Get child tag types
        """
        pass

    def test_v1_references_teams_get(self) -> None:
        """Test case for v1_references_teams_get

        Get teams (paginated)
        """
        pass


if __name__ == '__main__':
    unittest.main()
