# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_events_upcoming_events_post_request import V1EventsUpcomingEventsPostRequest

class TestV1EventsUpcomingEventsPostRequest(unittest.TestCase):
    """V1EventsUpcomingEventsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1EventsUpcomingEventsPostRequest:
        """Test V1EventsUpcomingEventsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1EventsUpcomingEventsPostRequest`
        """
        model = V1EventsUpcomingEventsPostRequest()
        if include_optional:
            return V1EventsUpcomingEventsPostRequest(
                event_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                league_id = 1,
                league_key = '',
                page = 1,
                page_size = 1,
                sport_id = 1,
                sport_key = '',
                timezone = 'UTC'
            )
        else:
            return V1EventsUpcomingEventsPostRequest(
        )
        """

    def testV1EventsUpcomingEventsPostRequest(self):
        """Test V1EventsUpcomingEventsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
