# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.api.reporting_api import ReportingApi


class TestReportingApi(unittest.TestCase):
    """ReportingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReportingApi()

    def tearDown(self) -> None:
        pass

    def test_v1_affiliates_links_clicks_get(self) -> None:
        """Test case for v1_affiliates_links_clicks_get

        Impression/click rollups
        """
        pass

    def test_v1_affiliates_links_inventory_summary_get(self) -> None:
        """Test case for v1_affiliates_links_inventory_summary_get

        Inventory counts
        """
        pass


if __name__ == '__main__':
    unittest.main()
