# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.api.links_api import LinksApi


class TestLinksApi(unittest.TestCase):
    """LinksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LinksApi()

    def tearDown(self) -> None:
        pass

    def test_v1_affiliates_links_bulk_deactivate_post(self) -> None:
        """Test case for v1_affiliates_links_bulk_deactivate_post

        Bulk deactivate links by filter
        """
        pass

    def test_v1_affiliates_links_bulk_patch(self) -> None:
        """Test case for v1_affiliates_links_bulk_patch

        Bulk patch links by filter
        """
        pass

    def test_v1_affiliates_links_bulk_post(self) -> None:
        """Test case for v1_affiliates_links_bulk_post

        Bulk create/upsert links (JSON or CSV)
        """
        pass

    def test_v1_affiliates_links_jobs_get(self) -> None:
        """Test case for v1_affiliates_links_jobs_get

        List async bulk jobs
        """
        pass

    def test_v1_affiliates_links_jobs_job_id_get(self) -> None:
        """Test case for v1_affiliates_links_jobs_job_id_get

        Poll an async bulk job
        """
        pass

    def test_v1_affiliates_links_post(self) -> None:
        """Test case for v1_affiliates_links_post

        Create or upsert a single link
        """
        pass


if __name__ == '__main__':
    unittest.main()
