# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.api.odds_api import OddsApi


class TestOddsApi(unittest.TestCase):
    """OddsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OddsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_odds_upcoming_odds_by_event_post(self) -> None:
        """Test case for v1_odds_upcoming_odds_by_event_post

        Get upcoming odds by event
        """
        pass


if __name__ == '__main__':
    unittest.main()
