# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_account_api_keys_key_code_delete409_response import V1AccountApiKeysKeyCodeDelete409Response

class TestV1AccountApiKeysKeyCodeDelete409Response(unittest.TestCase):
    """V1AccountApiKeysKeyCodeDelete409Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AccountApiKeysKeyCodeDelete409Response:
        """Test V1AccountApiKeysKeyCodeDelete409Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AccountApiKeysKeyCodeDelete409Response`
        """
        model = V1AccountApiKeysKeyCodeDelete409Response()
        if include_optional:
            return V1AccountApiKeysKeyCodeDelete409Response(
                error = '',
                success = True
            )
        else:
            return V1AccountApiKeysKeyCodeDelete409Response(
                error = '',
                success = True,
        )
        """

    def testV1AccountApiKeysKeyCodeDelete409Response(self):
        """Test V1AccountApiKeysKeyCodeDelete409Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
