# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.auth_set_check_endpoint_request import AuthSetCheckEndpointRequest

class TestAuthSetCheckEndpointRequest(unittest.TestCase):
    """AuthSetCheckEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthSetCheckEndpointRequest:
        """Test AuthSetCheckEndpointRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthSetCheckEndpointRequest`
        """
        model = AuthSetCheckEndpointRequest()
        if include_optional:
            return AuthSetCheckEndpointRequest(
                allow_multiple = True,
                auth_header_name = 'G',
                auth_scheme = 'GqWzyBAw2ZuufUOHOEhA8I',
                auth_token = '01234567',
                method = 'POST',
                url = ''
            )
        else:
            return AuthSetCheckEndpointRequest(
                auth_token = '01234567',
                method = 'POST',
                url = '',
        )
        """

    def testAuthSetCheckEndpointRequest(self):
        """Test AuthSetCheckEndpointRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
