# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_references_tag_dimensions_get200_response import V1ReferencesTagDimensionsGet200Response

class TestV1ReferencesTagDimensionsGet200Response(unittest.TestCase):
    """V1ReferencesTagDimensionsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ReferencesTagDimensionsGet200Response:
        """Test V1ReferencesTagDimensionsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ReferencesTagDimensionsGet200Response`
        """
        model = V1ReferencesTagDimensionsGet200Response()
        if include_optional:
            return V1ReferencesTagDimensionsGet200Response(
                records = [
                    None
                    ]
            )
        else:
            return V1ReferencesTagDimensionsGet200Response(
        )
        """

    def testV1ReferencesTagDimensionsGet200Response(self):
        """Test V1ReferencesTagDimensionsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
