# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.trends_quote_sandbox_response import TrendsQuoteSandboxResponse

class TestTrendsQuoteSandboxResponse(unittest.TestCase):
    """TrendsQuoteSandboxResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrendsQuoteSandboxResponse:
        """Test TrendsQuoteSandboxResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrendsQuoteSandboxResponse`
        """
        model = TrendsQuoteSandboxResponse()
        if include_optional:
            return TrendsQuoteSandboxResponse(
                american_odds_value = '',
                button_payload = '',
                decimal_odds_value = 1.337,
                event_betting_market_position_maps = [
                    None
                    ],
                flow_id = 56,
                flow_type = '',
                fractional_odds_value = '',
                is_combinable = True,
                odds_implied_probability = 1.337,
                parlay_failure_reason = 'one or more legs failed',
                payout_multiplier = 1.337
            )
        else:
            return TrendsQuoteSandboxResponse(
                event_betting_market_position_maps = [
                    None
                    ],
                flow_id = 56,
                flow_type = '',
        )
        """

    def testTrendsQuoteSandboxResponse(self):
        """Test TrendsQuoteSandboxResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
