# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.auth_o_auth_login_request import AuthOAuthLoginRequest

class TestAuthOAuthLoginRequest(unittest.TestCase):
    """AuthOAuthLoginRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthOAuthLoginRequest:
        """Test AuthOAuthLoginRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthOAuthLoginRequest`
        """
        model = AuthOAuthLoginRequest()
        if include_optional:
            return AuthOAuthLoginRequest(
                client_id = '',
                client_secret = ''
            )
        else:
            return AuthOAuthLoginRequest(
                client_id = '',
                client_secret = '',
        )
        """

    def testAuthOAuthLoginRequest(self):
        """Test AuthOAuthLoginRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
