# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.api.historical_api import HistoricalApi


class TestHistoricalApi(unittest.TestCase):
    """HistoricalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HistoricalApi()

    def tearDown(self) -> None:
        pass

    def test_v1_historical_events_get(self) -> None:
        """Test case for v1_historical_events_get

        List historical odds events (paginated)
        """
        pass

    def test_v1_historical_odds_event_id_ext_get(self) -> None:
        """Test case for v1_historical_odds_event_id_ext_get

        Download a per-event historical odds file
        """
        pass


if __name__ == '__main__':
    unittest.main()
