# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.api.offers_api import OffersApi


class TestOffersApi(unittest.TestCase):
    """OffersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OffersApi()

    def tearDown(self) -> None:
        pass

    def test_v1_affiliates_deals_post(self) -> None:
        """Test case for v1_affiliates_deals_post

        Paginated client deals
        """
        pass

    def test_v1_affiliates_offers_post(self) -> None:
        """Test case for v1_affiliates_offers_post

        Client offer cards for a geography
        """
        pass


if __name__ == '__main__':
    unittest.main()
