# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_odds_upcoming_odds_by_event_post_request import V1OddsUpcomingOddsByEventPostRequest

class TestV1OddsUpcomingOddsByEventPostRequest(unittest.TestCase):
    """V1OddsUpcomingOddsByEventPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1OddsUpcomingOddsByEventPostRequest:
        """Test V1OddsUpcomingOddsByEventPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1OddsUpcomingOddsByEventPostRequest`
        """
        model = V1OddsUpcomingOddsByEventPostRequest()
        if include_optional:
            return V1OddsUpcomingOddsByEventPostRequest(
                event_id = 1,
                operator_ids = [
                    1
                    ],
                page = 1,
                page_size = 1
            )
        else:
            return V1OddsUpcomingOddsByEventPostRequest(
                event_id = 1,
        )
        """

    def testV1OddsUpcomingOddsByEventPostRequest(self):
        """Test V1OddsUpcomingOddsByEventPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
