# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_trends_flows_by_id_post_request import V1TrendsFlowsByIdPostRequest

class TestV1TrendsFlowsByIdPostRequest(unittest.TestCase):
    """V1TrendsFlowsByIdPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TrendsFlowsByIdPostRequest:
        """Test V1TrendsFlowsByIdPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TrendsFlowsByIdPostRequest`
        """
        model = V1TrendsFlowsByIdPostRequest()
        if include_optional:
            return V1TrendsFlowsByIdPostRequest(
                fact_flow_type = 'base',
                flow_ids = [
                    1
                    ],
                flow_type = 'fact_flow',
                use_cartoon_images = True
            )
        else:
            return V1TrendsFlowsByIdPostRequest(
                flow_ids = [
                    1
                    ],
                flow_type = 'fact_flow',
        )
        """

    def testV1TrendsFlowsByIdPostRequest(self):
        """Test V1TrendsFlowsByIdPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
