# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.trends_error_response_error import TrendsErrorResponseError

class TestTrendsErrorResponseError(unittest.TestCase):
    """TrendsErrorResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrendsErrorResponseError:
        """Test TrendsErrorResponseError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrendsErrorResponseError`
        """
        model = TrendsErrorResponseError()
        if include_optional:
            return TrendsErrorResponseError(
                code = 'BAD_REQUEST',
                message = ''
            )
        else:
            return TrendsErrorResponseError(
                code = 'BAD_REQUEST',
                message = '',
        )
        """

    def testTrendsErrorResponseError(self):
        """Test TrendsErrorResponseError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
