# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_affiliates_links_post_request import V1AffiliatesLinksPostRequest

class TestV1AffiliatesLinksPostRequest(unittest.TestCase):
    """V1AffiliatesLinksPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AffiliatesLinksPostRequest:
        """Test V1AffiliatesLinksPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AffiliatesLinksPostRequest`
        """
        model = V1AffiliatesLinksPostRequest()
        if include_optional:
            return V1AffiliatesLinksPostRequest(
                android_deep_link_url = '',
                country_code = 'US',
                ios_deep_link_url = '',
                is_active = True,
                offer_call_to_action = '',
                offer_campaign = '',
                offer_category_id = 56,
                offer_display_bullets = [
                    ''
                    ],
                offer_display_small_print = '',
                offer_ev_usd = 1.337,
                offer_label = '',
                offer_priority = 56,
                offer_tagline = '',
                operator_id = 56,
                operator_name = '',
                source_network_affiliate_partner_id = 56,
                subnational_region_code = '',
                web_deep_link_url = ''
            )
        else:
            return V1AffiliatesLinksPostRequest(
                offer_category_id = 56,
                web_deep_link_url = '',
        )
        """

    def testV1AffiliatesLinksPostRequest(self):
        """Test V1AffiliatesLinksPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
