# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.api.trends_api import TrendsApi


class TestTrendsApi(unittest.TestCase):
    """TrendsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrendsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_trends_by_betting_market_position_post(self) -> None:
        """Test case for v1_trends_by_betting_market_position_post

        Get flows by betting market position IDs
        """
        pass

    def test_v1_trends_flow_graph_data_fact_flow_id_get(self) -> None:
        """Test case for v1_trends_flow_graph_data_fact_flow_id_get

        Get fact flow graph data
        """
        pass

    def test_v1_trends_flow_tooltip_flow_type_flow_id_get(self) -> None:
        """Test case for v1_trends_flow_tooltip_flow_type_flow_id_get

        Get flow tooltip payload
        """
        pass

    def test_v1_trends_flows_by_id_post(self) -> None:
        """Test case for v1_trends_flows_by_id_post

        Get flows by ids
        """
        pass

    def test_v1_trends_flows_post(self) -> None:
        """Test case for v1_trends_flows_post

        Get flows (paginated)
        """
        pass

    def test_v1_trends_flows_quote_post(self) -> None:
        """Test case for v1_trends_flows_quote_post

        Quote a batch of flows against the caller's configured check endpoint
        """
        pass

    def test_v1_trends_flows_quote_sandbox_post(self) -> None:
        """Test case for v1_trends_flows_quote_sandbox_post

        Mock operator pricing endpoint — for sandbox / development use
        """
        pass

    def test_v1_trends_leagues_with_available_flows_get(self) -> None:
        """Test case for v1_trends_leagues_with_available_flows_get

        Get leagues with available flows
        """
        pass

    def test_v1_trends_mixed_flows_post(self) -> None:
        """Test case for v1_trends_mixed_flows_post

        Get mixed flows (paginated)
        """
        pass

    def test_v1_trends_widget_event_post(self) -> None:
        """Test case for v1_trends_widget_event_post

        Submit a widget telemetry event
        """
        pass


if __name__ == '__main__':
    unittest.main()
