# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_trends_flows_post_request import V1TrendsFlowsPostRequest

class TestV1TrendsFlowsPostRequest(unittest.TestCase):
    """V1TrendsFlowsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TrendsFlowsPostRequest:
        """Test V1TrendsFlowsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TrendsFlowsPostRequest`
        """
        model = V1TrendsFlowsPostRequest()
        if include_optional:
            return V1TrendsFlowsPostRequest(
                bet_type = 'singles',
                betting_market_category_id = 1,
                betting_market_category_ids = [
                    1
                    ],
                betting_market_entity_type = 'player',
                betting_market_ids = [
                    1
                    ],
                betting_market_position_id = 1,
                betting_market_position_ids = [
                    1
                    ],
                event_id = 1,
                event_ids = [
                    1
                    ],
                event_start_date_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                event_start_date_to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                fact_flow_type = 'base',
                flow_type = 'fact',
                focus_entity_type_id = 1,
                full_hit_rate = True,
                include_alt_lines = True,
                include_deeplinks = True,
                include_only_basic_trends = True,
                include_star_sign_content = True,
                league_id = 1,
                league_ids = [
                    1
                    ],
                league_key = '',
                likelihood_type = 'likely',
                max_hit_rate_threshold = 0,
                max_implied_probability_threshold = 1.337,
                min_hit_rate_threshold = 0,
                min_implied_probability_threshold = 1.337,
                odds_format = 'american',
                operator_ids = [
                    1
                    ],
                operator_keys = [
                    ''
                    ],
                page = 1,
                page_size = 1,
                player_id = 1,
                player_ids = [
                    1
                    ],
                player_key = '',
                product_mode = 'sportsbook',
                split_type = 'overs',
                sport_id = 1,
                sport_ids = [
                    1
                    ],
                sport_key = '',
                starting_soon = True,
                team_id = 1,
                team_ids = [
                    1
                    ],
                team_key = '',
                team_split = '',
                use_cartoon_images = True
            )
        else:
            return V1TrendsFlowsPostRequest(
        )
        """

    def testV1TrendsFlowsPostRequest(self):
        """Test V1TrendsFlowsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
