# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_affiliates_links_bulk_post202_response import V1AffiliatesLinksBulkPost202Response

class TestV1AffiliatesLinksBulkPost202Response(unittest.TestCase):
    """V1AffiliatesLinksBulkPost202Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AffiliatesLinksBulkPost202Response:
        """Test V1AffiliatesLinksBulkPost202Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AffiliatesLinksBulkPost202Response`
        """
        model = V1AffiliatesLinksBulkPost202Response()
        if include_optional:
            return V1AffiliatesLinksBulkPost202Response(
                job_id = '',
                mode = 'async',
                poll_url = '',
                status = 'queued',
                submitted_rows = 56
            )
        else:
            return V1AffiliatesLinksBulkPost202Response(
        )
        """

    def testV1AffiliatesLinksBulkPost202Response(self):
        """Test V1AffiliatesLinksBulkPost202Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
