# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.trends_quote_sandbox_request import TrendsQuoteSandboxRequest

class TestTrendsQuoteSandboxRequest(unittest.TestCase):
    """TrendsQuoteSandboxRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrendsQuoteSandboxRequest:
        """Test TrendsQuoteSandboxRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrendsQuoteSandboxRequest`
        """
        model = TrendsQuoteSandboxRequest()
        if include_optional:
            return TrendsQuoteSandboxRequest(
                country = '01',
                event_betting_market_position_maps = [
                    None
                    ],
                flow_id = 56,
                flow_type = 'fact_flow',
                region = '01'
            )
        else:
            return TrendsQuoteSandboxRequest(
                country = '01',
                event_betting_market_position_maps = [
                    None
                    ],
                flow_id = 56,
                flow_type = 'fact_flow',
        )
        """

    def testTrendsQuoteSandboxRequest(self):
        """Test TrendsQuoteSandboxRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
