# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.affiliate_error_response import AffiliateErrorResponse

class TestAffiliateErrorResponse(unittest.TestCase):
    """AffiliateErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AffiliateErrorResponse:
        """Test AffiliateErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AffiliateErrorResponse`
        """
        model = AffiliateErrorResponse()
        if include_optional:
            return AffiliateErrorResponse(
                error = odditt_api_client.models.affiliate_error_response_error.affiliate_ErrorResponse_error(
                    code = 'BAD_REQUEST', 
                    message = '', )
            )
        else:
            return AffiliateErrorResponse(
                error = odditt_api_client.models.affiliate_error_response_error.affiliate_ErrorResponse_error(
                    code = 'BAD_REQUEST', 
                    message = '', ),
        )
        """

    def testAffiliateErrorResponse(self):
        """Test AffiliateErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
