# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.api.lookups_api import LookupsApi


class TestLookupsApi(unittest.TestCase):
    """LookupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LookupsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_affiliates_lookups_affiliate_networks_get(self) -> None:
        """Test case for v1_affiliates_lookups_affiliate_networks_get

        Affiliate networks
        """
        pass

    def test_v1_affiliates_lookups_offer_categories_get(self) -> None:
        """Test case for v1_affiliates_lookups_offer_categories_get

        Offer categories
        """
        pass

    def test_v1_affiliates_lookups_operator_jurisdictions_get(self) -> None:
        """Test case for v1_affiliates_lookups_operator_jurisdictions_get

        Operator jurisdictions
        """
        pass

    def test_v1_affiliates_lookups_operators_get(self) -> None:
        """Test case for v1_affiliates_lookups_operators_get

        Operators
        """
        pass


if __name__ == '__main__':
    unittest.main()
