# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.api.affiliates_api import AffiliatesApi


class TestAffiliatesApi(unittest.TestCase):
    """AffiliatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AffiliatesApi()

    def tearDown(self) -> None:
        pass

    def test_v1_affiliates_event_position_post(self) -> None:
        """Test case for v1_affiliates_event_position_post

        Single-bet cart for affiliate mode
        """
        pass

    def test_v1_affiliates_parlay_post(self) -> None:
        """Test case for v1_affiliates_parlay_post

        Parlay cart for affiliate mode
        """
        pass


if __name__ == '__main__':
    unittest.main()
