# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_v1_account_api_keys_get(self) -> None:
        """Test case for v1_account_api_keys_get

        List own API keys
        """
        pass

    def test_v1_account_api_keys_key_code_delete(self) -> None:
        """Test case for v1_account_api_keys_key_code_delete

        Deactivate an API key
        """
        pass

    def test_v1_account_api_keys_post(self) -> None:
        """Test case for v1_account_api_keys_post

        Create a new API key
        """
        pass

    def test_v1_account_check_endpoint_delete(self) -> None:
        """Test case for v1_account_check_endpoint_delete

        Delete the check endpoint
        """
        pass

    def test_v1_account_check_endpoint_get(self) -> None:
        """Test case for v1_account_check_endpoint_get

        Get the configured check endpoint
        """
        pass

    def test_v1_account_check_endpoint_post(self) -> None:
        """Test case for v1_account_check_endpoint_post

        Set the check endpoint (upsert)
        """
        pass

    def test_v1_account_config_get(self) -> None:
        """Test case for v1_account_config_get

        Get own client configuration
        """
        pass

    def test_v1_account_secret_post(self) -> None:
        """Test case for v1_account_secret_post

        Create a new client secret
        """
        pass

    def test_v1_account_secrets_get(self) -> None:
        """Test case for v1_account_secrets_get

        List own client secrets
        """
        pass

    def test_v1_account_secrets_secret_code_delete(self) -> None:
        """Test case for v1_account_secrets_secret_code_delete

        Delete a client secret
        """
        pass

    def test_v1_account_usage_get(self) -> None:
        """Test case for v1_account_usage_get

        Get own usage stats
        """
        pass


if __name__ == '__main__':
    unittest.main()
