# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.auth_list_secrets_response import AuthListSecretsResponse

class TestAuthListSecretsResponse(unittest.TestCase):
    """AuthListSecretsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthListSecretsResponse:
        """Test AuthListSecretsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthListSecretsResponse`
        """
        model = AuthListSecretsResponse()
        if include_optional:
            return AuthListSecretsResponse(
                secrets = [
                    odditt_api_client.models.auth_list_secrets_response_secrets_inner.auth_ListSecretsResponse_secrets_inner(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        secret_code = '', 
                        secret_preview = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                success = True
            )
        else:
            return AuthListSecretsResponse(
        )
        """

    def testAuthListSecretsResponse(self):
        """Test AuthListSecretsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
