# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_affiliates_links_bulk_deactivate_post_request import V1AffiliatesLinksBulkDeactivatePostRequest

class TestV1AffiliatesLinksBulkDeactivatePostRequest(unittest.TestCase):
    """V1AffiliatesLinksBulkDeactivatePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AffiliatesLinksBulkDeactivatePostRequest:
        """Test V1AffiliatesLinksBulkDeactivatePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AffiliatesLinksBulkDeactivatePostRequest`
        """
        model = V1AffiliatesLinksBulkDeactivatePostRequest()
        if include_optional:
            return V1AffiliatesLinksBulkDeactivatePostRequest(
                filter = None
            )
        else:
            return V1AffiliatesLinksBulkDeactivatePostRequest(
                filter = None,
        )
        """

    def testV1AffiliatesLinksBulkDeactivatePostRequest(self):
        """Test V1AffiliatesLinksBulkDeactivatePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
