# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odditt_api_client.models.v1_affiliates_offers_post_request import V1AffiliatesOffersPostRequest

class TestV1AffiliatesOffersPostRequest(unittest.TestCase):
    """V1AffiliatesOffersPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AffiliatesOffersPostRequest:
        """Test V1AffiliatesOffersPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AffiliatesOffersPostRequest`
        """
        model = V1AffiliatesOffersPostRequest()
        if include_optional:
            return V1AffiliatesOffersPostRequest(
                country_code = 'US',
                excluded_operator_ids = [
                    56
                    ],
                hide_offers_links = True,
                offer_campaign = '',
                operator_ids = [
                    56
                    ],
                operator_keys = [
                    ''
                    ],
                operator_type_ids = [
                    56
                    ],
                subnational_region_code = ''
            )
        else:
            return V1AffiliatesOffersPostRequest(
        )
        """

    def testV1AffiliatesOffersPostRequest(self):
        """Test V1AffiliatesOffersPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
