# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AuthSetCheckEndpointRequest(BaseModel):
    """
    AuthSetCheckEndpointRequest
    """ # noqa: E501
    allow_multiple: Optional[StrictBool] = Field(default=False, description="If true, the platform sends a single POST with a JSON array of all hydrated payloads. If false (default), one POST per flow is issued in parallel.")
    auth_header_name: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="HTTP header name used to carry the authentication credential. Defaults to 'Authorization'. Common alternatives: 'X-API-Key', 'X-Auth'.")
    auth_scheme: Optional[Annotated[str, Field(strict=True, max_length=32)]] = Field(default=None, description="Prefix placed before the token in the header value. Defaults to 'Bearer' when 'auth_header_name' is omitted. Set to an empty string for headers that take the raw value (e.g. 'X-API-Key').")
    auth_token: Annotated[str, Field(min_length=8, strict=True)] = Field(description="Authentication credential. Stored server-side and never returned in any response. Sent as `<auth_header_name>: <auth_scheme> <auth_token>` (scheme omitted when empty).")
    method: StrictStr = Field(description="HTTP method used when calling the endpoint.")
    url: StrictStr = Field(description="Absolute URL of the check endpoint (https recommended).")
    __properties: ClassVar[List[str]] = ["allow_multiple", "auth_header_name", "auth_scheme", "auth_token", "method", "url"]

    @field_validator('auth_header_name')
    def auth_header_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9-]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9-]+$/")
        return value

    @field_validator('auth_scheme')
    def auth_scheme_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9-]*$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9-]*$/")
        return value

    @field_validator('method')
    def method_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['POST']):
            raise ValueError("must be one of enum values ('POST')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuthSetCheckEndpointRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuthSetCheckEndpointRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allow_multiple": obj.get("allow_multiple") if obj.get("allow_multiple") is not None else False,
            "auth_header_name": obj.get("auth_header_name"),
            "auth_scheme": obj.get("auth_scheme"),
            "auth_token": obj.get("auth_token"),
            "method": obj.get("method"),
            "url": obj.get("url")
        })
        return _obj


