# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TrendsErrorResponseError(BaseModel):
    """
    TrendsErrorResponseError
    """ # noqa: E501
    code: StrictStr = Field(description="Machine-readable error code. Possible values:   * `BAD_REQUEST` — malformed request, invalid path/query parameter, or JSON type mismatch in the body. Returned with HTTP 400.   * `VALIDATION_ERROR` — one or more request fields failed validation rules; the message names each offending field. Returned with HTTP 422 (Unprocessable Entity).   * `AMBIGUOUS_LOOKUP` — a slug identifier matched more than one record; qualify it (e.g. `country/league`) and retry.   * `UNAUTHORIZED` — missing or invalid credentials.   * `FORBIDDEN` — authenticated but not permitted to access this resource.   * `NOT_FOUND` — resource does not exist.   * `RATE_LIMIT_EXCEEDED` — too many requests.   * `INTERNAL_ERROR` — unexpected server error. ")
    message: StrictStr = Field(description="Human-readable explanation of the error. For `VALIDATION_ERROR` responses, names the offending field(s) and the rule that failed.")
    __properties: ClassVar[List[str]] = ["code", "message"]

    @field_validator('code')
    def code_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['BAD_REQUEST', 'VALIDATION_ERROR', 'AMBIGUOUS_LOOKUP', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'RATE_LIMIT_EXCEEDED', 'INTERNAL_ERROR']):
            raise ValueError("must be one of enum values ('BAD_REQUEST', 'VALIDATION_ERROR', 'AMBIGUOUS_LOOKUP', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'RATE_LIMIT_EXCEEDED', 'INTERNAL_ERROR')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrendsErrorResponseError from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrendsErrorResponseError from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "message": obj.get("message")
        })
        return _obj


