# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TrendsWidgetEventRequest(BaseModel):
    """
    TrendsWidgetEventRequest
    """ # noqa: E501
    event_body: Dict[str, Any] = Field(description="Arbitrary JSON object carrying event-specific fields. May be an empty object.")
    event_type: StrictStr = Field(description="The kind of client-side widget interaction being reported.")
    mode: Optional[StrictStr] = Field(default=None, description="Optional widget mode the interaction occurred in. Defaults to `clean`.")
    __properties: ClassVar[List[str]] = ["event_body", "event_type", "mode"]

    @field_validator('event_type')
    def event_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['impression', 'click', 'dwell', 'cart_open', 'cart_offers_shown', 'cart_dismiss', 'card_click', 'graph_expand', 'graph_metric_change', 'filter_change', 'widget-impression', 'widget-viewed', 'betslip-clicked', 'betslip-shared', 'flow-clicked', 'flow-shared']):
            raise ValueError("must be one of enum values ('impression', 'click', 'dwell', 'cart_open', 'cart_offers_shown', 'cart_dismiss', 'card_click', 'graph_expand', 'graph_metric_change', 'filter_change', 'widget-impression', 'widget-viewed', 'betslip-clicked', 'betslip-shared', 'flow-clicked', 'flow-shared')")
        return value

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['operator', 'affiliate', 'clean']):
            raise ValueError("must be one of enum values ('operator', 'affiliate', 'clean')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrendsWidgetEventRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrendsWidgetEventRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_body": obj.get("event_body"),
            "event_type": obj.get("event_type"),
            "mode": obj.get("mode")
        })
        return _obj


