# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TrendsQuoteSandboxResponse(BaseModel):
    """
    Mock pricing response. Shape differs between single (1-leg) and parlay (2+ legs); parlay responses additionally carry top-level combined odds and is_combinable / parlay_failure_reason.
    """ # noqa: E501
    american_odds_value: Optional[StrictStr] = Field(default=None, description="Parlay only. Null when uncombinable.")
    button_payload: Optional[StrictStr] = Field(default=None, description="Synthetic bet-slip identifier (prefix 'FD-MOCK-'). Null when the result is invalid or the parlay is uncombinable.")
    decimal_odds_value: Optional[Union[StrictFloat, StrictInt]] = None
    event_betting_market_position_maps: List[Dict[str, Any]]
    flow_id: StrictInt
    flow_type: StrictStr
    fractional_odds_value: Optional[StrictStr] = None
    is_combinable: Optional[StrictBool] = Field(default=None, description="Parlay only. False if any leg failed or the parlay-level uncombinable roll fired.")
    odds_implied_probability: Optional[Union[StrictFloat, StrictInt]] = None
    parlay_failure_reason: Optional[StrictStr] = None
    payout_multiplier: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["american_odds_value", "button_payload", "decimal_odds_value", "event_betting_market_position_maps", "flow_id", "flow_type", "fractional_odds_value", "is_combinable", "odds_implied_probability", "parlay_failure_reason", "payout_multiplier"]

    @field_validator('parlay_failure_reason')
    def parlay_failure_reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['one or more legs failed', 'selections are not combinable']):
            raise ValueError("must be one of enum values ('one or more legs failed', 'selections are not combinable')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrendsQuoteSandboxResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if american_odds_value (nullable) is None
        # and model_fields_set contains the field
        if self.american_odds_value is None and "american_odds_value" in self.model_fields_set:
            _dict['american_odds_value'] = None

        # set to None if button_payload (nullable) is None
        # and model_fields_set contains the field
        if self.button_payload is None and "button_payload" in self.model_fields_set:
            _dict['button_payload'] = None

        # set to None if decimal_odds_value (nullable) is None
        # and model_fields_set contains the field
        if self.decimal_odds_value is None and "decimal_odds_value" in self.model_fields_set:
            _dict['decimal_odds_value'] = None

        # set to None if fractional_odds_value (nullable) is None
        # and model_fields_set contains the field
        if self.fractional_odds_value is None and "fractional_odds_value" in self.model_fields_set:
            _dict['fractional_odds_value'] = None

        # set to None if odds_implied_probability (nullable) is None
        # and model_fields_set contains the field
        if self.odds_implied_probability is None and "odds_implied_probability" in self.model_fields_set:
            _dict['odds_implied_probability'] = None

        # set to None if parlay_failure_reason (nullable) is None
        # and model_fields_set contains the field
        if self.parlay_failure_reason is None and "parlay_failure_reason" in self.model_fields_set:
            _dict['parlay_failure_reason'] = None

        # set to None if payout_multiplier (nullable) is None
        # and model_fields_set contains the field
        if self.payout_multiplier is None and "payout_multiplier" in self.model_fields_set:
            _dict['payout_multiplier'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrendsQuoteSandboxResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "american_odds_value": obj.get("american_odds_value"),
            "button_payload": obj.get("button_payload"),
            "decimal_odds_value": obj.get("decimal_odds_value"),
            "event_betting_market_position_maps": obj.get("event_betting_market_position_maps"),
            "flow_id": obj.get("flow_id"),
            "flow_type": obj.get("flow_type"),
            "fractional_odds_value": obj.get("fractional_odds_value"),
            "is_combinable": obj.get("is_combinable"),
            "odds_implied_probability": obj.get("odds_implied_probability"),
            "parlay_failure_reason": obj.get("parlay_failure_reason"),
            "payout_multiplier": obj.get("payout_multiplier")
        })
        return _obj


