# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TrendsQuoteSandboxRequest(BaseModel):
    """
    Single hydrated pricing payload — the exact shape /v1/trends/flows/quote sends in each outbound call. Wire this endpoint into /v1/account/check-endpoint to round-trip the widget call entirely on platform infrastructure (no real operator needed).
    """ # noqa: E501
    country: Annotated[str, Field(min_length=2, strict=True, max_length=2)]
    event_betting_market_position_maps: List[Dict[str, Any]] = Field(description="Hydrated leg array, identical to what the quote endpoint POSTs to a real operator. Pass it through unchanged.")
    flow_id: StrictInt
    flow_type: StrictStr
    region: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=3)]] = None
    __properties: ClassVar[List[str]] = ["country", "event_betting_market_position_maps", "flow_id", "flow_type", "region"]

    @field_validator('flow_type')
    def flow_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['fact_flow', 'fun_flow', 'fact_flow_parlay', 'fun_flow_parlay', 'plain_flow_parlay']):
            raise ValueError("must be one of enum values ('fact_flow', 'fun_flow', 'fact_flow_parlay', 'fun_flow_parlay', 'plain_flow_parlay')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrendsQuoteSandboxRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrendsQuoteSandboxRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "country": obj.get("country"),
            "event_betting_market_position_maps": obj.get("event_betting_market_position_maps"),
            "flow_id": obj.get("flow_id"),
            "flow_type": obj.get("flow_type"),
            "region": obj.get("region")
        })
        return _obj


