# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1AffiliatesLinksPostRequest(BaseModel):
    """
    V1AffiliatesLinksPostRequest
    """ # noqa: E501
    android_deep_link_url: Optional[StrictStr] = None
    country_code: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=2)]] = 'US'
    ios_deep_link_url: Optional[StrictStr] = None
    is_active: Optional[StrictBool] = True
    offer_call_to_action: Optional[StrictStr] = None
    offer_campaign: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    offer_category_id: StrictInt
    offer_display_bullets: Optional[List[StrictStr]] = None
    offer_display_small_print: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    offer_ev_usd: Optional[Union[StrictFloat, StrictInt]] = None
    offer_label: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    offer_priority: Optional[StrictInt] = None
    offer_tagline: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    operator_id: Optional[StrictInt] = Field(default=None, description="One of operator_id or operator_name is required.")
    operator_name: Optional[StrictStr] = None
    source_network_affiliate_partner_id: Optional[StrictInt] = None
    subnational_region_code: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="Omit for country-grain inventory.")
    web_deep_link_url: StrictStr
    __properties: ClassVar[List[str]] = ["android_deep_link_url", "country_code", "ios_deep_link_url", "is_active", "offer_call_to_action", "offer_campaign", "offer_category_id", "offer_display_bullets", "offer_display_small_print", "offer_ev_usd", "offer_label", "offer_priority", "offer_tagline", "operator_id", "operator_name", "source_network_affiliate_partner_id", "subnational_region_code", "web_deep_link_url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1AffiliatesLinksPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1AffiliatesLinksPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "android_deep_link_url": obj.get("android_deep_link_url"),
            "country_code": obj.get("country_code") if obj.get("country_code") is not None else 'US',
            "ios_deep_link_url": obj.get("ios_deep_link_url"),
            "is_active": obj.get("is_active") if obj.get("is_active") is not None else True,
            "offer_call_to_action": obj.get("offer_call_to_action"),
            "offer_campaign": obj.get("offer_campaign"),
            "offer_category_id": obj.get("offer_category_id"),
            "offer_display_bullets": obj.get("offer_display_bullets"),
            "offer_display_small_print": obj.get("offer_display_small_print"),
            "offer_ev_usd": obj.get("offer_ev_usd"),
            "offer_label": obj.get("offer_label"),
            "offer_priority": obj.get("offer_priority"),
            "offer_tagline": obj.get("offer_tagline"),
            "operator_id": obj.get("operator_id"),
            "operator_name": obj.get("operator_name"),
            "source_network_affiliate_partner_id": obj.get("source_network_affiliate_partner_id"),
            "subnational_region_code": obj.get("subnational_region_code"),
            "web_deep_link_url": obj.get("web_deep_link_url")
        })
        return _obj


