# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1AffiliatesEventPositionPostRequest(BaseModel):
    """
    V1AffiliatesEventPositionPostRequest
    """ # noqa: E501
    country_code: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=2)]] = Field(default='US', description="ISO 3166-1 alpha-2 country code.")
    event_betting_market_position_id: Annotated[int, Field(strict=True, ge=1)] = Field(description="The event betting market position to build the cart for.")
    hide_offers_links: Optional[StrictBool] = Field(default=None, description="When true, offer metadata is returned without the deep-link URLs.")
    odds_format: Optional[StrictStr] = Field(default=None, description="Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).")
    offer_campaign: Optional[StrictStr] = Field(default=None, description="Optional campaign filter. Renders only offers tagged with this campaign.")
    operator_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Optional list of operator IDs to gate which operators appear in the cart.")
    operator_keys: Optional[List[StrictStr]] = Field(default=None, description="Optional operator external keys (e.g. 'draftkings'). Resolved IDs are merged with operator_ids.")
    product_mode: Optional[StrictStr] = Field(default=None, description="Display mode. dfs rewrites leg stat lines to MORE/LESS.")
    subnational_region_code: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="ISO 3166-2 subnational region code (used for offer/deeplink resolution).")
    use_cartoon_images: Optional[StrictBool] = Field(default=None, description="When true, swaps default operator/jersey imagery for cartoon variants.")
    __properties: ClassVar[List[str]] = ["country_code", "event_betting_market_position_id", "hide_offers_links", "odds_format", "offer_campaign", "operator_ids", "operator_keys", "product_mode", "subnational_region_code", "use_cartoon_images"]

    @field_validator('odds_format')
    def odds_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['american', 'decimal', 'fractional', 'multiplier', 'percent']):
            raise ValueError("must be one of enum values ('american', 'decimal', 'fractional', 'multiplier', 'percent')")
        return value

    @field_validator('product_mode')
    def product_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['sportsbook', 'dfs', 'prediction_market']):
            raise ValueError("must be one of enum values ('sportsbook', 'dfs', 'prediction_market')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1AffiliatesEventPositionPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1AffiliatesEventPositionPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "country_code": obj.get("country_code") if obj.get("country_code") is not None else 'US',
            "event_betting_market_position_id": obj.get("event_betting_market_position_id"),
            "hide_offers_links": obj.get("hide_offers_links"),
            "odds_format": obj.get("odds_format"),
            "offer_campaign": obj.get("offer_campaign"),
            "operator_ids": obj.get("operator_ids"),
            "operator_keys": obj.get("operator_keys"),
            "product_mode": obj.get("product_mode"),
            "subnational_region_code": obj.get("subnational_region_code"),
            "use_cartoon_images": obj.get("use_cartoon_images")
        })
        return _obj


