# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1AffiliatesDealsPostRequest(BaseModel):
    """
    V1AffiliatesDealsPostRequest
    """ # noqa: E501
    country_code: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=2)]] = 'US'
    excluded_operator_ids: Optional[List[StrictInt]] = None
    hide_offers_links: Optional[StrictBool] = None
    mode: Optional[StrictStr] = 'carousel'
    offer_campaign: Optional[StrictStr] = None
    offer_type: Optional[StrictStr] = 'sports'
    operator_ids: Optional[List[StrictInt]] = None
    operator_keys: Optional[List[StrictStr]] = None
    operator_type_ids: Optional[List[StrictInt]] = None
    page_number: Optional[Annotated[int, Field(strict=True, ge=1)]] = 1
    page_size: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = 20
    subnational_region_code: Optional[Annotated[str, Field(strict=True, max_length=10)]] = None
    with_reviews: Optional[StrictBool] = Field(default=None, description="When true")
    __properties: ClassVar[List[str]] = ["country_code", "excluded_operator_ids", "hide_offers_links", "mode", "offer_campaign", "offer_type", "operator_ids", "operator_keys", "operator_type_ids", "page_number", "page_size", "subnational_region_code", "with_reviews"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['carousel', 'featured', 'list']):
            raise ValueError("must be one of enum values ('carousel', 'featured', 'list')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1AffiliatesDealsPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1AffiliatesDealsPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "country_code": obj.get("country_code") if obj.get("country_code") is not None else 'US',
            "excluded_operator_ids": obj.get("excluded_operator_ids"),
            "hide_offers_links": obj.get("hide_offers_links"),
            "mode": obj.get("mode") if obj.get("mode") is not None else 'carousel',
            "offer_campaign": obj.get("offer_campaign"),
            "offer_type": obj.get("offer_type") if obj.get("offer_type") is not None else 'sports',
            "operator_ids": obj.get("operator_ids"),
            "operator_keys": obj.get("operator_keys"),
            "operator_type_ids": obj.get("operator_type_ids"),
            "page_number": obj.get("page_number") if obj.get("page_number") is not None else 1,
            "page_size": obj.get("page_size") if obj.get("page_size") is not None else 20,
            "subnational_region_code": obj.get("subnational_region_code"),
            "with_reviews": obj.get("with_reviews")
        })
        return _obj


