# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1AffiliatesEventsPostRequest(BaseModel):
    """
    V1AffiliatesEventsPostRequest
    """ # noqa: E501
    country_code: Annotated[str, Field(min_length=2, strict=True, max_length=2)]
    device_type: Optional[StrictStr] = None
    event_type: StrictStr
    offer_campaign: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    offer_id: UUID
    offer_label: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    operator_id: Annotated[int, Field(strict=True, ge=1)]
    session_token: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    subnational_region_code: Optional[Annotated[str, Field(strict=True, max_length=10)]] = None
    __properties: ClassVar[List[str]] = ["country_code", "device_type", "event_type", "offer_campaign", "offer_id", "offer_label", "operator_id", "session_token", "subnational_region_code"]

    @field_validator('device_type')
    def device_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ios', 'android', 'desktop']):
            raise ValueError("must be one of enum values ('ios', 'android', 'desktop')")
        return value

    @field_validator('event_type')
    def event_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['impression', 'click']):
            raise ValueError("must be one of enum values ('impression', 'click')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1AffiliatesEventsPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1AffiliatesEventsPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "country_code": obj.get("country_code"),
            "device_type": obj.get("device_type"),
            "event_type": obj.get("event_type"),
            "offer_campaign": obj.get("offer_campaign"),
            "offer_id": obj.get("offer_id"),
            "offer_label": obj.get("offer_label"),
            "operator_id": obj.get("operator_id"),
            "session_token": obj.get("session_token"),
            "subnational_region_code": obj.get("subnational_region_code")
        })
        return _obj


