# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1EventsUpcomingEventsPostRequest(BaseModel):
    """
    V1EventsUpcomingEventsPostRequest
    """ # noqa: E501
    event_date: Optional[date] = Field(default=None, description="Filter by event date (YYYY-MM-DD). Defaults to today (UTC).")
    league_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    league_key: Optional[StrictStr] = Field(default=None, description="League external key (e.g. 'nba', 'united-states.nba'). Alternative to league_id. If both are provided, league_id takes precedence.")
    page: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=1, description="Page number for pagination")
    page_size: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=100, description="Number of events per page")
    sport_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    sport_key: Optional[StrictStr] = Field(default=None, description="Sport external key (e.g. 'american-football'). Alternative to sport_id. If both are provided, sport_id takes precedence.")
    timezone: Optional[StrictStr] = Field(default='UTC', description="IANA timezone for date interpretation (e.g. 'UTC', 'America/New_York', 'Europe/London')")
    __properties: ClassVar[List[str]] = ["event_date", "league_id", "league_key", "page", "page_size", "sport_id", "sport_key", "timezone"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1EventsUpcomingEventsPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1EventsUpcomingEventsPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_date": obj.get("event_date"),
            "league_id": obj.get("league_id"),
            "league_key": obj.get("league_key"),
            "page": obj.get("page") if obj.get("page") is not None else 1,
            "page_size": obj.get("page_size") if obj.get("page_size") is not None else 100,
            "sport_id": obj.get("sport_id"),
            "sport_key": obj.get("sport_key"),
            "timezone": obj.get("timezone") if obj.get("timezone") is not None else 'UTC'
        })
        return _obj


