# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1TrendsByBettingMarketPositionPostRequest(BaseModel):
    """
    V1TrendsByBettingMarketPositionPostRequest
    """ # noqa: E501
    event_betting_market_position_ids: Annotated[List[Annotated[int, Field(strict=True, ge=1)]], Field(min_length=1)] = Field(description="Array of event betting market position IDs")
    odds_format: Optional[StrictStr] = Field(default=None, description="Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).")
    product_mode: Optional[StrictStr] = Field(default=None, description="Display mode. dfs rewrites stat lines to MORE/LESS; on the paginated flows endpoints it also auto-filters to over/under player props (entity_type=player, positions [4,5]) unless an entity/position filter is set.")
    use_cartoon_images: Optional[StrictBool] = Field(default=None, description="When true, the logo fields on each flow, leg, and multi-trend slot (default_logo_url, logo_url_1, logo_url_2) are replaced with cartoon-jersey image URLs derived from the relevant team, player, or league. When false or omitted, the original logo URLs are returned. Defaults to false.")
    __properties: ClassVar[List[str]] = ["event_betting_market_position_ids", "odds_format", "product_mode", "use_cartoon_images"]

    @field_validator('odds_format')
    def odds_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['american', 'decimal', 'fractional', 'multiplier', 'percent']):
            raise ValueError("must be one of enum values ('american', 'decimal', 'fractional', 'multiplier', 'percent')")
        return value

    @field_validator('product_mode')
    def product_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['sportsbook', 'dfs', 'prediction_market']):
            raise ValueError("must be one of enum values ('sportsbook', 'dfs', 'prediction_market')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1TrendsByBettingMarketPositionPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1TrendsByBettingMarketPositionPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_betting_market_position_ids": obj.get("event_betting_market_position_ids"),
            "odds_format": obj.get("odds_format"),
            "product_mode": obj.get("product_mode"),
            "use_cartoon_images": obj.get("use_cartoon_images")
        })
        return _obj


