# coding: utf-8

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1TrendsFlowsPostRequest(BaseModel):
    """
    V1TrendsFlowsPostRequest
    """ # noqa: E501
    bet_type: Optional[StrictStr] = Field(default=None, description="Filter by bet type. If omitted, returns mixed singles and parlays.")
    betting_market_category_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Deprecated — use `betting_market_category_ids` instead (e.g. Shooting Props, Game Props etc.). A bare `betting_market_category_id` is treated as `betting_market_category_ids: [betting_market_category_id]`.")
    betting_market_category_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Filter by one or more betting market category IDs (e.g. Shooting Props, Game Props etc.). Empty array = no filter.")
    betting_market_entity_type: Optional[StrictStr] = Field(default=None, description="Filter by betting market entity type")
    betting_market_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Filter by betting market IDs")
    betting_market_position_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Deprecated — use `betting_market_position_ids` instead. A bare `betting_market_position_id` is treated as `betting_market_position_ids: [betting_market_position_id]`.")
    betting_market_position_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Filter by one or more betting market position IDs. Empty array = no filter.")
    event_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Deprecated — use `event_ids` instead. A bare `event_id` is treated as `event_ids: [event_id]`.")
    event_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Filter by one or more event IDs. Empty array = no filter.")
    event_start_date_from: Optional[datetime] = Field(default=None, description="Filter events starting on or after this value. Accepts a date ('2026-04-19') or full ISO 8601 timestamp ('2026-04-19T00:00:00Z').")
    event_start_date_to: Optional[datetime] = Field(default=None, description="Filter events starting on or before this value. Accepts a date ('2026-04-26') or full ISO 8601 timestamp ('2026-04-26T23:59:59Z').")
    fact_flow_type: Optional[StrictStr] = Field(default=None, description="Sub-type for fact flows. Defaults to 'base' if omitted.")
    flow_type: Optional[StrictStr] = Field(default=None, description="Type of flow to return. 'plain' only returns parlays.")
    focus_entity_type_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Filter by focus entity type ID")
    full_hit_rate: Optional[StrictBool] = Field(default=None, description="When true, include full hit rate data in response")
    include_alt_lines: Optional[StrictBool] = Field(default=None, description="When false, exclude alt lines. Defaults to true.")
    include_deeplinks: Optional[StrictBool] = Field(default=None, description="When true, returns operator-specific odds and deeplink URLs (bet_ios_deep_link_url, bet_android_deep_link_url, bet_web_deep_link_url) for each flow. Requires exactly one operator_id in operator_ids.")
    include_only_basic_trends: Optional[StrictBool] = Field(default=None, description="When true, return only basic trends (omit fact flows with conditions)")
    include_star_sign_content: Optional[StrictBool] = Field(default=None, description="When true, include star sign/horoscope content in flows")
    league_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Deprecated — use `league_ids` instead. A bare `league_id` is treated as `league_ids: [league_id]`.")
    league_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Filter by one or more league IDs. Empty array = no filter.")
    league_key: Optional[StrictStr] = Field(default=None, description="League external key (e.g. 'nba', 'united-states.nba'). Format: {league_key} or {country_key}.{league_key}. Alternative to league_id. If both are provided, league_id takes precedence.")
    likelihood_type: Optional[StrictStr] = Field(default=None, description="Filter by likelihood category")
    max_hit_rate_threshold: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="Maximum hit rate threshold filter (0-100)")
    max_implied_probability_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Maximum implied probability threshold filter")
    min_hit_rate_threshold: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="Minimum hit rate threshold filter (0-100)")
    min_implied_probability_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Minimum implied probability threshold filter")
    odds_format: Optional[StrictStr] = Field(default=None, description="Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).")
    operator_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Filter by operator IDs")
    operator_keys: Optional[List[StrictStr]] = Field(default=None, description="Filter by operator external keys (e.g. 'draftkings'). Format: {operator_key}. Resolved IDs are merged with operator_ids.")
    page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    page_size: Optional[Annotated[int, Field(le=25, strict=True, ge=1)]] = None
    player_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Deprecated — use `player_ids` instead. A bare `player_id` is treated as `player_ids: [player_id]`.")
    player_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Filter by one or more player IDs. Empty array = no filter.")
    player_key: Optional[StrictStr] = Field(default=None, description="Player external key (e.g. 'nikola-vucevic', 'chicago-bulls.tre-jones', 'nba.boston-celtics.nikola-vucevic'). Format: {player_key} or {team_key}.{player_key} or {league_key}.{team_key}.{player_key}. Alternative to player_id. If both are provided, player_id takes precedence.")
    product_mode: Optional[StrictStr] = Field(default=None, description="Display mode. dfs rewrites stat lines to MORE/LESS; on the paginated flows endpoints it also auto-filters to over/under player props (entity_type=player, positions [4,5]) unless an entity/position filter is set.")
    split_type: Optional[StrictStr] = Field(default=None, description="Filter by split type (overs or unders)")
    sport_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Deprecated — use `sport_ids` instead. A bare `sport_id` is treated as `sport_ids: [sport_id]`.")
    sport_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Filter by one or more sport IDs. Empty array = no filter.")
    sport_key: Optional[StrictStr] = Field(default=None, description="Sport external key (e.g. 'american-football'). Format: {sport_key}. Alternative to sport_id. If both are provided, sport_id takes precedence.")
    starting_soon: Optional[StrictBool] = Field(default=None, description="When true, only return flows for events starting soon")
    team_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Deprecated — use `team_ids` instead. A bare `team_id` is treated as `team_ids: [team_id]`.")
    team_ids: Optional[List[Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Filter by one or more team IDs. Empty array = no filter.")
    team_key: Optional[StrictStr] = Field(default=None, description="Team external key (e.g. 'new-england-patriots', 'nfl.new-england-patriots'). Format: {team_key} or {league_key}.{team_key}. Alternative to team_id. If both are provided, team_id takes precedence.")
    team_split: Optional[StrictStr] = Field(default=None, description="Team split filter value")
    use_cartoon_images: Optional[StrictBool] = Field(default=None, description="When true, the logo fields on each flow, leg, and multi-trend slot (default_logo_url, logo_url_1, logo_url_2) are replaced with cartoon-jersey image URLs derived from the relevant team, player, or league. When false or omitted, the original logo URLs are returned. Defaults to false.")
    __properties: ClassVar[List[str]] = ["bet_type", "betting_market_category_id", "betting_market_category_ids", "betting_market_entity_type", "betting_market_ids", "betting_market_position_id", "betting_market_position_ids", "event_id", "event_ids", "event_start_date_from", "event_start_date_to", "fact_flow_type", "flow_type", "focus_entity_type_id", "full_hit_rate", "include_alt_lines", "include_deeplinks", "include_only_basic_trends", "include_star_sign_content", "league_id", "league_ids", "league_key", "likelihood_type", "max_hit_rate_threshold", "max_implied_probability_threshold", "min_hit_rate_threshold", "min_implied_probability_threshold", "odds_format", "operator_ids", "operator_keys", "page", "page_size", "player_id", "player_ids", "player_key", "product_mode", "split_type", "sport_id", "sport_ids", "sport_key", "starting_soon", "team_id", "team_ids", "team_key", "team_split", "use_cartoon_images"]

    @field_validator('bet_type')
    def bet_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['singles', 'parlay', 'same_game_parlay']):
            raise ValueError("must be one of enum values ('singles', 'parlay', 'same_game_parlay')")
        return value

    @field_validator('betting_market_entity_type')
    def betting_market_entity_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['player', 'team', 'event']):
            raise ValueError("must be one of enum values ('player', 'team', 'event')")
        return value

    @field_validator('fact_flow_type')
    def fact_flow_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['base', 'expanded', 'multi']):
            raise ValueError("must be one of enum values ('base', 'expanded', 'multi')")
        return value

    @field_validator('flow_type')
    def flow_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['fact', 'fun', 'plain']):
            raise ValueError("must be one of enum values ('fact', 'fun', 'plain')")
        return value

    @field_validator('likelihood_type')
    def likelihood_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['likely', 'possible', 'longshot']):
            raise ValueError("must be one of enum values ('likely', 'possible', 'longshot')")
        return value

    @field_validator('odds_format')
    def odds_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['american', 'decimal', 'fractional', 'multiplier', 'percent']):
            raise ValueError("must be one of enum values ('american', 'decimal', 'fractional', 'multiplier', 'percent')")
        return value

    @field_validator('product_mode')
    def product_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['sportsbook', 'dfs', 'prediction_market']):
            raise ValueError("must be one of enum values ('sportsbook', 'dfs', 'prediction_market')")
        return value

    @field_validator('split_type')
    def split_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['overs', 'unders']):
            raise ValueError("must be one of enum values ('overs', 'unders')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1TrendsFlowsPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1TrendsFlowsPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bet_type": obj.get("bet_type"),
            "betting_market_category_id": obj.get("betting_market_category_id"),
            "betting_market_category_ids": obj.get("betting_market_category_ids"),
            "betting_market_entity_type": obj.get("betting_market_entity_type"),
            "betting_market_ids": obj.get("betting_market_ids"),
            "betting_market_position_id": obj.get("betting_market_position_id"),
            "betting_market_position_ids": obj.get("betting_market_position_ids"),
            "event_id": obj.get("event_id"),
            "event_ids": obj.get("event_ids"),
            "event_start_date_from": obj.get("event_start_date_from"),
            "event_start_date_to": obj.get("event_start_date_to"),
            "fact_flow_type": obj.get("fact_flow_type"),
            "flow_type": obj.get("flow_type"),
            "focus_entity_type_id": obj.get("focus_entity_type_id"),
            "full_hit_rate": obj.get("full_hit_rate"),
            "include_alt_lines": obj.get("include_alt_lines"),
            "include_deeplinks": obj.get("include_deeplinks"),
            "include_only_basic_trends": obj.get("include_only_basic_trends"),
            "include_star_sign_content": obj.get("include_star_sign_content"),
            "league_id": obj.get("league_id"),
            "league_ids": obj.get("league_ids"),
            "league_key": obj.get("league_key"),
            "likelihood_type": obj.get("likelihood_type"),
            "max_hit_rate_threshold": obj.get("max_hit_rate_threshold"),
            "max_implied_probability_threshold": obj.get("max_implied_probability_threshold"),
            "min_hit_rate_threshold": obj.get("min_hit_rate_threshold"),
            "min_implied_probability_threshold": obj.get("min_implied_probability_threshold"),
            "odds_format": obj.get("odds_format"),
            "operator_ids": obj.get("operator_ids"),
            "operator_keys": obj.get("operator_keys"),
            "page": obj.get("page"),
            "page_size": obj.get("page_size"),
            "player_id": obj.get("player_id"),
            "player_ids": obj.get("player_ids"),
            "player_key": obj.get("player_key"),
            "product_mode": obj.get("product_mode"),
            "split_type": obj.get("split_type"),
            "sport_id": obj.get("sport_id"),
            "sport_ids": obj.get("sport_ids"),
            "sport_key": obj.get("sport_key"),
            "starting_soon": obj.get("starting_soon"),
            "team_id": obj.get("team_id"),
            "team_ids": obj.get("team_ids"),
            "team_key": obj.get("team_key"),
            "team_split": obj.get("team_split"),
            "use_cartoon_images": obj.get("use_cartoon_images")
        })
        return _obj


