# coding: utf-8

# flake8: noqa

"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "AccountApi",
    "AffiliatesApi",
    "AuthenticationApi",
    "EventsApi",
    "HistoricalApi",
    "LinksApi",
    "LookupsApi",
    "OddsApi",
    "OffersApi",
    "ReferencesApi",
    "ReportingApi",
    "TelemetryApi",
    "TrendsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AffiliateErrorResponse",
    "AffiliateErrorResponseError",
    "AuthCheckEndpointResponse",
    "AuthCheckEndpointResponseData",
    "AuthCreateAPIKeyRequest",
    "AuthCreateAPIKeyResponse",
    "AuthCreateSecretResponse",
    "AuthErrorResponse",
    "AuthListAPIKeysResponse",
    "AuthListAPIKeysResponseApiKeysInner",
    "AuthListSecretsResponse",
    "AuthListSecretsResponseSecretsInner",
    "AuthOAuthLoginRequest",
    "AuthRefreshRequest",
    "AuthSetCheckEndpointRequest",
    "AuthTokenPair",
    "TrendsErrorResponse",
    "TrendsErrorResponseError",
    "TrendsPaginatedResponse",
    "TrendsQuoteFlowItem",
    "TrendsQuoteItemResult",
    "TrendsQuoteSandboxRequest",
    "TrendsQuoteSandboxResponse",
    "TrendsWidgetEventRequest",
    "TrendsWidgetEventResponse",
    "V1AccountApiKeysKeyCodeDelete409Response",
    "V1AffiliatesDealsPostRequest",
    "V1AffiliatesEventPositionPostRequest",
    "V1AffiliatesEventsPostRequest",
    "V1AffiliatesLinksBulkDeactivatePostRequest",
    "V1AffiliatesLinksBulkPatchRequest",
    "V1AffiliatesLinksBulkPost202Response",
    "V1AffiliatesLinksPostRequest",
    "V1AffiliatesOffersPostRequest",
    "V1AffiliatesParlayPostRequest",
    "V1EventsUpcomingEventsPostRequest",
    "V1OddsUpcomingOddsByEventPostRequest",
    "V1ReferencesTagDimensionsGet200Response",
    "V1ReferencesTagTypesTagTypeIdChildrenGet200Response",
    "V1TrendsByBettingMarketPositionPostRequest",
    "V1TrendsFlowsByIdPostRequest",
    "V1TrendsFlowsPostRequest",
]

# import apis into sdk package
from odditt_api_client.api.account_api import AccountApi as AccountApi
from odditt_api_client.api.affiliates_api import AffiliatesApi as AffiliatesApi
from odditt_api_client.api.authentication_api import AuthenticationApi as AuthenticationApi
from odditt_api_client.api.events_api import EventsApi as EventsApi
from odditt_api_client.api.historical_api import HistoricalApi as HistoricalApi
from odditt_api_client.api.links_api import LinksApi as LinksApi
from odditt_api_client.api.lookups_api import LookupsApi as LookupsApi
from odditt_api_client.api.odds_api import OddsApi as OddsApi
from odditt_api_client.api.offers_api import OffersApi as OffersApi
from odditt_api_client.api.references_api import ReferencesApi as ReferencesApi
from odditt_api_client.api.reporting_api import ReportingApi as ReportingApi
from odditt_api_client.api.telemetry_api import TelemetryApi as TelemetryApi
from odditt_api_client.api.trends_api import TrendsApi as TrendsApi

# import ApiClient
from odditt_api_client.api_response import ApiResponse as ApiResponse
from odditt_api_client.api_client import ApiClient as ApiClient
from odditt_api_client.configuration import Configuration as Configuration
from odditt_api_client.exceptions import OpenApiException as OpenApiException
from odditt_api_client.exceptions import ApiTypeError as ApiTypeError
from odditt_api_client.exceptions import ApiValueError as ApiValueError
from odditt_api_client.exceptions import ApiKeyError as ApiKeyError
from odditt_api_client.exceptions import ApiAttributeError as ApiAttributeError
from odditt_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from odditt_api_client.models.affiliate_error_response import AffiliateErrorResponse as AffiliateErrorResponse
from odditt_api_client.models.affiliate_error_response_error import AffiliateErrorResponseError as AffiliateErrorResponseError
from odditt_api_client.models.auth_check_endpoint_response import AuthCheckEndpointResponse as AuthCheckEndpointResponse
from odditt_api_client.models.auth_check_endpoint_response_data import AuthCheckEndpointResponseData as AuthCheckEndpointResponseData
from odditt_api_client.models.auth_create_api_key_request import AuthCreateAPIKeyRequest as AuthCreateAPIKeyRequest
from odditt_api_client.models.auth_create_api_key_response import AuthCreateAPIKeyResponse as AuthCreateAPIKeyResponse
from odditt_api_client.models.auth_create_secret_response import AuthCreateSecretResponse as AuthCreateSecretResponse
from odditt_api_client.models.auth_error_response import AuthErrorResponse as AuthErrorResponse
from odditt_api_client.models.auth_list_api_keys_response import AuthListAPIKeysResponse as AuthListAPIKeysResponse
from odditt_api_client.models.auth_list_api_keys_response_api_keys_inner import AuthListAPIKeysResponseApiKeysInner as AuthListAPIKeysResponseApiKeysInner
from odditt_api_client.models.auth_list_secrets_response import AuthListSecretsResponse as AuthListSecretsResponse
from odditt_api_client.models.auth_list_secrets_response_secrets_inner import AuthListSecretsResponseSecretsInner as AuthListSecretsResponseSecretsInner
from odditt_api_client.models.auth_o_auth_login_request import AuthOAuthLoginRequest as AuthOAuthLoginRequest
from odditt_api_client.models.auth_refresh_request import AuthRefreshRequest as AuthRefreshRequest
from odditt_api_client.models.auth_set_check_endpoint_request import AuthSetCheckEndpointRequest as AuthSetCheckEndpointRequest
from odditt_api_client.models.auth_token_pair import AuthTokenPair as AuthTokenPair
from odditt_api_client.models.trends_error_response import TrendsErrorResponse as TrendsErrorResponse
from odditt_api_client.models.trends_error_response_error import TrendsErrorResponseError as TrendsErrorResponseError
from odditt_api_client.models.trends_paginated_response import TrendsPaginatedResponse as TrendsPaginatedResponse
from odditt_api_client.models.trends_quote_flow_item import TrendsQuoteFlowItem as TrendsQuoteFlowItem
from odditt_api_client.models.trends_quote_item_result import TrendsQuoteItemResult as TrendsQuoteItemResult
from odditt_api_client.models.trends_quote_sandbox_request import TrendsQuoteSandboxRequest as TrendsQuoteSandboxRequest
from odditt_api_client.models.trends_quote_sandbox_response import TrendsQuoteSandboxResponse as TrendsQuoteSandboxResponse
from odditt_api_client.models.trends_widget_event_request import TrendsWidgetEventRequest as TrendsWidgetEventRequest
from odditt_api_client.models.trends_widget_event_response import TrendsWidgetEventResponse as TrendsWidgetEventResponse
from odditt_api_client.models.v1_account_api_keys_key_code_delete409_response import V1AccountApiKeysKeyCodeDelete409Response as V1AccountApiKeysKeyCodeDelete409Response
from odditt_api_client.models.v1_affiliates_deals_post_request import V1AffiliatesDealsPostRequest as V1AffiliatesDealsPostRequest
from odditt_api_client.models.v1_affiliates_event_position_post_request import V1AffiliatesEventPositionPostRequest as V1AffiliatesEventPositionPostRequest
from odditt_api_client.models.v1_affiliates_events_post_request import V1AffiliatesEventsPostRequest as V1AffiliatesEventsPostRequest
from odditt_api_client.models.v1_affiliates_links_bulk_deactivate_post_request import V1AffiliatesLinksBulkDeactivatePostRequest as V1AffiliatesLinksBulkDeactivatePostRequest
from odditt_api_client.models.v1_affiliates_links_bulk_patch_request import V1AffiliatesLinksBulkPatchRequest as V1AffiliatesLinksBulkPatchRequest
from odditt_api_client.models.v1_affiliates_links_bulk_post202_response import V1AffiliatesLinksBulkPost202Response as V1AffiliatesLinksBulkPost202Response
from odditt_api_client.models.v1_affiliates_links_post_request import V1AffiliatesLinksPostRequest as V1AffiliatesLinksPostRequest
from odditt_api_client.models.v1_affiliates_offers_post_request import V1AffiliatesOffersPostRequest as V1AffiliatesOffersPostRequest
from odditt_api_client.models.v1_affiliates_parlay_post_request import V1AffiliatesParlayPostRequest as V1AffiliatesParlayPostRequest
from odditt_api_client.models.v1_events_upcoming_events_post_request import V1EventsUpcomingEventsPostRequest as V1EventsUpcomingEventsPostRequest
from odditt_api_client.models.v1_odds_upcoming_odds_by_event_post_request import V1OddsUpcomingOddsByEventPostRequest as V1OddsUpcomingOddsByEventPostRequest
from odditt_api_client.models.v1_references_tag_dimensions_get200_response import V1ReferencesTagDimensionsGet200Response as V1ReferencesTagDimensionsGet200Response
from odditt_api_client.models.v1_references_tag_types_tag_type_id_children_get200_response import V1ReferencesTagTypesTagTypeIdChildrenGet200Response as V1ReferencesTagTypesTagTypeIdChildrenGet200Response
from odditt_api_client.models.v1_trends_by_betting_market_position_post_request import V1TrendsByBettingMarketPositionPostRequest as V1TrendsByBettingMarketPositionPostRequest
from odditt_api_client.models.v1_trends_flows_by_id_post_request import V1TrendsFlowsByIdPostRequest as V1TrendsFlowsByIdPostRequest
from odditt_api_client.models.v1_trends_flows_post_request import V1TrendsFlowsPostRequest as V1TrendsFlowsPostRequest

