"""
    Odditt B2B Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr, field_validator
from typing import Any, Dict, Optional
from typing_extensions import Annotated

from odditt_api_client.api_client import ApiClient, RequestSerialized
from odditt_api_client.api_response import ApiResponse
from odditt_api_client.rest import RESTResponseType


class HistoricalApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def v1_historical_events_get(
        self,
        schema_version: Annotated[Optional[StrictStr], Field(description="Payload schema version. Defaults to `v1` when omitted. Unknown versions are rejected.")] = None,
        sport_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        league_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        team_id: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Filter to events involving this team as either home or away.")] = None,
        start_date: Annotated[Optional[StrictStr], Field(description="Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD.")] = None,
        end_date: Annotated[Optional[StrictStr], Field(description="Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD.")] = None,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        page_size: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """List historical odds events (paginated)

        Returns a paginated catalog of per-event historical odds files the authenticated client has access to. Each result entry carries pre-baked download URLs for the JSON and CSV payloads; clients GET those URLs directly. Results are scoped to the authenticated client; callers without a client association receive `403 Forbidden`. 

        :param schema_version: Payload schema version. Defaults to `v1` when omitted. Unknown versions are rejected.
        :type schema_version: str
        :param sport_id:
        :type sport_id: int
        :param league_id:
        :type league_id: int
        :param team_id: Filter to events involving this team as either home or away.
        :type team_id: int
        :param start_date: Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD.
        :type start_date: str
        :param end_date: Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD.
        :type end_date: str
        :param page:
        :type page: int
        :param page_size:
        :type page_size: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_historical_events_get_serialize(
            schema_version=schema_version,
            sport_id=sport_id,
            league_id=league_id,
            team_id=team_id,
            start_date=start_date,
            end_date=end_date,
            page=page,
            page_size=page_size,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '401': "TrendsErrorResponse",
            '403': "TrendsErrorResponse",
            '422': "TrendsErrorResponse",
            '500': "TrendsErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def v1_historical_events_get_with_http_info(
        self,
        schema_version: Annotated[Optional[StrictStr], Field(description="Payload schema version. Defaults to `v1` when omitted. Unknown versions are rejected.")] = None,
        sport_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        league_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        team_id: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Filter to events involving this team as either home or away.")] = None,
        start_date: Annotated[Optional[StrictStr], Field(description="Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD.")] = None,
        end_date: Annotated[Optional[StrictStr], Field(description="Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD.")] = None,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        page_size: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """List historical odds events (paginated)

        Returns a paginated catalog of per-event historical odds files the authenticated client has access to. Each result entry carries pre-baked download URLs for the JSON and CSV payloads; clients GET those URLs directly. Results are scoped to the authenticated client; callers without a client association receive `403 Forbidden`. 

        :param schema_version: Payload schema version. Defaults to `v1` when omitted. Unknown versions are rejected.
        :type schema_version: str
        :param sport_id:
        :type sport_id: int
        :param league_id:
        :type league_id: int
        :param team_id: Filter to events involving this team as either home or away.
        :type team_id: int
        :param start_date: Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD.
        :type start_date: str
        :param end_date: Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD.
        :type end_date: str
        :param page:
        :type page: int
        :param page_size:
        :type page_size: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_historical_events_get_serialize(
            schema_version=schema_version,
            sport_id=sport_id,
            league_id=league_id,
            team_id=team_id,
            start_date=start_date,
            end_date=end_date,
            page=page,
            page_size=page_size,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '401': "TrendsErrorResponse",
            '403': "TrendsErrorResponse",
            '422': "TrendsErrorResponse",
            '500': "TrendsErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def v1_historical_events_get_without_preload_content(
        self,
        schema_version: Annotated[Optional[StrictStr], Field(description="Payload schema version. Defaults to `v1` when omitted. Unknown versions are rejected.")] = None,
        sport_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        league_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        team_id: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Filter to events involving this team as either home or away.")] = None,
        start_date: Annotated[Optional[StrictStr], Field(description="Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD.")] = None,
        end_date: Annotated[Optional[StrictStr], Field(description="Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD.")] = None,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        page_size: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List historical odds events (paginated)

        Returns a paginated catalog of per-event historical odds files the authenticated client has access to. Each result entry carries pre-baked download URLs for the JSON and CSV payloads; clients GET those URLs directly. Results are scoped to the authenticated client; callers without a client association receive `403 Forbidden`. 

        :param schema_version: Payload schema version. Defaults to `v1` when omitted. Unknown versions are rejected.
        :type schema_version: str
        :param sport_id:
        :type sport_id: int
        :param league_id:
        :type league_id: int
        :param team_id: Filter to events involving this team as either home or away.
        :type team_id: int
        :param start_date: Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD.
        :type start_date: str
        :param end_date: Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD.
        :type end_date: str
        :param page:
        :type page: int
        :param page_size:
        :type page_size: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_historical_events_get_serialize(
            schema_version=schema_version,
            sport_id=sport_id,
            league_id=league_id,
            team_id=team_id,
            start_date=start_date,
            end_date=end_date,
            page=page,
            page_size=page_size,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '401': "TrendsErrorResponse",
            '403': "TrendsErrorResponse",
            '422': "TrendsErrorResponse",
            '500': "TrendsErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v1_historical_events_get_serialize(
        self,
        schema_version,
        sport_id,
        league_id,
        team_id,
        start_date,
        end_date,
        page,
        page_size,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if schema_version is not None:
            
            _query_params.append(('schema_version', schema_version))
            
        if sport_id is not None:
            
            _query_params.append(('sport_id', sport_id))
            
        if league_id is not None:
            
            _query_params.append(('league_id', league_id))
            
        if team_id is not None:
            
            _query_params.append(('team_id', team_id))
            
        if start_date is not None:
            
            _query_params.append(('start_date', start_date))
            
        if end_date is not None:
            
            _query_params.append(('end_date', end_date))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if page_size is not None:
            
            _query_params.append(('page_size', page_size))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuth', 
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/historical/events',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def v1_historical_odds_event_id_ext_get(
        self,
        event_id: Annotated[int, Field(strict=True, ge=1, description="Canonical event identifier.")],
        ext: Annotated[StrictStr, Field(description="File format. `json` returns `application/json`; `csv` returns `text/csv`.")],
        schema_version: Annotated[Optional[StrictStr], Field(description="Payload schema version. Defaults to `v1` when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Download a per-event historical odds file

        Resolves the requested per-event file for the authenticated client and streams the JSON or CSV payload back. The response body is the raw file content (not the manifest envelope); the API takes care of fetching the bytes from the underlying CDN so callers see a single HTTP call per file.  The `sha256` of the bytes-at-rest is exposed as a strong `ETag`. Clients can short-circuit with `If-None-Match` to receive `304 Not Modified`. `Range` requests are forwarded upstream and `206 Partial Content` responses are relayed unchanged — useful for resuming multi-MB CSV downloads. 

        :param event_id: Canonical event identifier. (required)
        :type event_id: int
        :param ext: File format. `json` returns `application/json`; `csv` returns `text/csv`. (required)
        :type ext: str
        :param schema_version: Payload schema version. Defaults to `v1` when omitted.
        :type schema_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_historical_odds_event_id_ext_get_serialize(
            event_id=event_id,
            ext=ext,
            schema_version=schema_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '206': None,
            '304': None,
            '400': "TrendsErrorResponse",
            '401': "TrendsErrorResponse",
            '403': "TrendsErrorResponse",
            '404': "TrendsErrorResponse",
            '422': "TrendsErrorResponse",
            '500': "TrendsErrorResponse",
            '502': "TrendsErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def v1_historical_odds_event_id_ext_get_with_http_info(
        self,
        event_id: Annotated[int, Field(strict=True, ge=1, description="Canonical event identifier.")],
        ext: Annotated[StrictStr, Field(description="File format. `json` returns `application/json`; `csv` returns `text/csv`.")],
        schema_version: Annotated[Optional[StrictStr], Field(description="Payload schema version. Defaults to `v1` when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Download a per-event historical odds file

        Resolves the requested per-event file for the authenticated client and streams the JSON or CSV payload back. The response body is the raw file content (not the manifest envelope); the API takes care of fetching the bytes from the underlying CDN so callers see a single HTTP call per file.  The `sha256` of the bytes-at-rest is exposed as a strong `ETag`. Clients can short-circuit with `If-None-Match` to receive `304 Not Modified`. `Range` requests are forwarded upstream and `206 Partial Content` responses are relayed unchanged — useful for resuming multi-MB CSV downloads. 

        :param event_id: Canonical event identifier. (required)
        :type event_id: int
        :param ext: File format. `json` returns `application/json`; `csv` returns `text/csv`. (required)
        :type ext: str
        :param schema_version: Payload schema version. Defaults to `v1` when omitted.
        :type schema_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_historical_odds_event_id_ext_get_serialize(
            event_id=event_id,
            ext=ext,
            schema_version=schema_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '206': None,
            '304': None,
            '400': "TrendsErrorResponse",
            '401': "TrendsErrorResponse",
            '403': "TrendsErrorResponse",
            '404': "TrendsErrorResponse",
            '422': "TrendsErrorResponse",
            '500': "TrendsErrorResponse",
            '502': "TrendsErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def v1_historical_odds_event_id_ext_get_without_preload_content(
        self,
        event_id: Annotated[int, Field(strict=True, ge=1, description="Canonical event identifier.")],
        ext: Annotated[StrictStr, Field(description="File format. `json` returns `application/json`; `csv` returns `text/csv`.")],
        schema_version: Annotated[Optional[StrictStr], Field(description="Payload schema version. Defaults to `v1` when omitted.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Download a per-event historical odds file

        Resolves the requested per-event file for the authenticated client and streams the JSON or CSV payload back. The response body is the raw file content (not the manifest envelope); the API takes care of fetching the bytes from the underlying CDN so callers see a single HTTP call per file.  The `sha256` of the bytes-at-rest is exposed as a strong `ETag`. Clients can short-circuit with `If-None-Match` to receive `304 Not Modified`. `Range` requests are forwarded upstream and `206 Partial Content` responses are relayed unchanged — useful for resuming multi-MB CSV downloads. 

        :param event_id: Canonical event identifier. (required)
        :type event_id: int
        :param ext: File format. `json` returns `application/json`; `csv` returns `text/csv`. (required)
        :type ext: str
        :param schema_version: Payload schema version. Defaults to `v1` when omitted.
        :type schema_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._v1_historical_odds_event_id_ext_get_serialize(
            event_id=event_id,
            ext=ext,
            schema_version=schema_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '206': None,
            '304': None,
            '400': "TrendsErrorResponse",
            '401': "TrendsErrorResponse",
            '403': "TrendsErrorResponse",
            '404': "TrendsErrorResponse",
            '422': "TrendsErrorResponse",
            '500': "TrendsErrorResponse",
            '502': "TrendsErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _v1_historical_odds_event_id_ext_get_serialize(
        self,
        event_id,
        ext,
        schema_version,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if event_id is not None:
            _path_params['event_id'] = event_id
        if ext is not None:
            _path_params['ext'] = ext
        # process the query parameters
        if schema_version is not None:
            
            _query_params.append(('schema_version', schema_version))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/csv'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuth', 
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/historical/odds/{event_id}.{ext}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


